version: "2"
services:
  ui-layout:
    image: openlmis/dev-ui:7.0.0-RC1
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '.:/app'
    env_file: .env
    volumes_from:
      - auth-ui
      - ui-components
    depends_on:
      - auth-ui
      - ui-components
  auth-ui:
    image: openlmis/auth-ui:6.1.0-RC1
    volumes:
      - '/openlmis-auth-ui'
  ui-components:
    image: openlmis/ui-components:5.3.0-RC1
    volumes:
      - '/openlmis-ui-components'
  image:
    build: .
    image: openlmis/ui-layout
