version: "2"
services:
  ui-layout:
    image: openlmis/dev-ui:9.0.1-RC2
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '.:/app'
    env_file: .env
    volumes_from:
      - auth-ui
      - ui-components
    depends_on:
      - auth-ui
      - ui-components
  auth-ui:
    image: openlmis/auth-ui:6.2.1-RC2
    volumes:
      - '/openlmis-auth-ui'
  ui-components:
    image: openlmis/ui-components:7.2.0-RC2
    volumes:
      - '/openlmis-ui-components'
  image:
    build: .
    image: openlmis/ui-layout
